version: '3.7'

services:
  adonis-docker:
    build: .
    image: adonis_task_app
    container_name: adonis_task_app
    env_file: .env.example
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
volumes:
  dbdata:
